first_run: true

autostart:
  - name: discord
    sleep: 3

links:
  rinnos: https://gitlab.com/RinnOS/RinnOS.git
  dotfiles: https://gitlab.com/RinnOS/Dotfiles.git
  wallpapers: https://gitlab.com/RinnOS/Wallpapers.git

paths:
  localdotdir: /mnt/Vault/Dotfiles/Linux/Arch

drives:
  - Vault
  - BigDrive
  - Data

files:
  - ./packages.yaml
  - ./dotfiles.yaml
