first_run: true

autostart:
  - name: discord
    sleep: 3

links:
  dotfiles: https://github.com/Rinnray/Dotfiles.git
  wallpapers: https://gitlab.com/RinnOS/Wallpapers.git

paths:
  dotdir: ~/RinnOS/dotfiles
  localdotdir: /mnt/Vault/Dotfiles/Linux/Arch

drives:
  - Vault
  - BigDrive
  - Data

files:
  - ./packages.yaml
  - ./dotfiles.yaml
